## Database configurations
#
#database:
#      development:
#          host: localhost
#          port: 27017
#          user: ""
#          password: ""
#          database: caspian2
#
#      staging:
#          host: localhost
#          port: 27017
#          user: ""
#          password: ""
#          database: caspian2
#
#      production:
#          host: localhost
#          port: 27017
#          user: ""
#          password: ""
#          database: caspian2

database:
    development:
        host: kahana.mongohq.com
        port: 10015
        user: caspian
        password: xxxzxxxxx
        database: caspian2

    staging:
        host: kahana.mongohq.com
        port: 10015
        user: caspian
        password: xxxxxxx
        database: caspian2

    production:
        host: kahana.mongohq.com
        port: 10015
        user: caspian
        password: xxxxxx
        database: caspian2
