# Database configuration
#
# Define the database settings of the applicaition

development:
  host: localhost
  port: 27017
  user: ""
  password: ""
  database: caspian

staging:
  host: localhost
  port: 27017
  user: ""
  password: ""
  database: caspian

production:
  host: localhost
  port: 27017
  user: ""
  password: ""
  database: caspian